reload = False
daemon = False
workers = 4
bind = '0.0.0.0:9090'
loglevel = 'debug'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
accesslog = 'logs/access.log'
errorlog = 'logs/error.log'
control_socket = '.gunicorn/gunicorn.ctl'
