* Xtream Codes Proxy

This script proxy request to an external xtream codes server and filter results based on whitelist and blacklist.

It creates a local server to allow internal users fetch filtered streams.

The only API endpoint supported is: /player_api.php

About lists formats:
- Whitelist and blacklist are matched againt stream names.
- Whitelist-category is matches againts category_id.

** Configuration file example
This is a format for the configuration file.

The configuration file is formated in sections like "ini" a file. The repo provides a template
to use must be renamed from xtream_proxy.conf.template to xtream_proxy.conf.

The sections are:
1. xtream-remote : information about remote xtream codes server
   - server: remote server url scheme://host:port
   - user: remote server username
   - pass: remote server password
2. whitelist : allowed streams
   - one string per line
3. blacklist : blocked streams
   - one string per line
4. whitelist-category: entired category allowed
   - one number per line
    
*** Example: xtream_proxy.conf
[xtream-remote]
server = http://remote-server:8080
user = someuser
pass = somepass

[whitelist]
Cars
Deporte
Sport
Espn

[blacklist]
Adult

[whitelist-category]
188
163

