* Xtream Codes Proxy

This script proxy request to an external xtream codes server and
filter results based on whitelist and blacklist.

It creates a local server to allow internal users fetch filtered streams.

The only API endpoint supported is: /player_api.php

About lists formats:
- Whitelist and blacklist are matched againt stream names.
- Whitelist-category is matches againts category_id.

** Configuration file example
This is a format for the configuration file.

The configuration file is formated in sections like "ini" a file. The repo provides a template
to use must be renamed from xtream_proxy.conf.template to xtream_proxy.conf.

The sections are:
1. xtream-remote : information about remote xtream codes server
   - server: remote server url scheme://host:port
   - user: remote server username
   - pass: remote server password
2. whitelist : allowed streams
   - one string per line
3. blacklist : blocked streams
   - one string per line
4. whitelist-category: entired category allowed
   - one number per line
    
*** Example: xtream_proxy.conf
[xtream-remote]
server = http://remote-server:8080
user = someuser
pass = somepass
user-agent = UA-string

[whitelist]
Cars
Deporte
Sport
Espn

[blacklist]
Adult

[whitelist-category]
188
163


** Docker
*** Build
docker build -t iptv .

*** Debug
#+begin_src bash
  # when run the app, it must be mounted the configuration file
mkdir logs
docker run \
  --rm \
  -it \
  --net host \
  -v `pwd`/xtream_proxy.conf:/app/xtream_proxy.conf \
  -v `pwd`/logs:/app/logs \
  --name iptv \
  iptv bash

gunicorn --keyfile privkey.pem --certfile cert.pem -b:9090 xtream_proxy:app
#+end_src

*** Run
#+begin_src bash
mkdir logs
docker run \
  -d \
  --restart always \
  --net host \
  -v `pwd`/xtream_proxy.conf:/app/xtream_proxy.conf \
  -v `pwd`/logs:/app/logs \
  --name iptv \
  iptv
#+end_src

** Testing
curl -k https://127.0.0.1:9090/player_api.php
curl -k "https://127.0.0.1:9090/player_api.php?action=get_vod_categories"
curl -k "https://127.0.0.1:9090/player_api.php?action=get_vod_streams"


